// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwoosnxuaodyscoskyiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3b29zbnh1YW9keXNjb3NreWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg5NTEsImV4cCI6MjA2NTkxNDk1MX0.s_xJq5g5bsWy0oV1Kdw9qNu3_HqWI9WHKAoEfz_-ZNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);